baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
defaultContentLanguage = 'en'
## disableLanguages = ['nl']

##Languages code
[Language]

  #This is English
  [languages.en]
  contentDir = 'content/english'
  languageName = 'EN'
  weight  = 20
  languagedirection = 'rtl'

  [[languages.en.menu.navmenu]]
    name = 'BASIC INSIGHT'
    url = '/basic-insight'
    weight = 1
  [[languages.en.menu.navmenu]]
    name = "Analyses"
    url = "/analyses"
    weight = 2
  [[languages.en.menu.navmenu]]
    name = "Blog"
    url = "/blog"
    weight = 3
  [[languages.en.menu.navmenu]]
    name = "About"
    url = "/about"
    weight = 4

  #This is Dutch
  [languages.nl]
  contentDir = 'content/Dutch'
  languageName = 'NL'
  weight  = 5

  #This is Dutch
  [languages.fr]
  contentDir = 'content/French'
  languageName = 'FR'
  weight  = 5




##Taxonomies
[taxonomies]
  Tag= 'tags'
  Category= 'categories'
  Author = "authors"

## Navigation Menu Configuration



## Logo Configuration, Favicon, Alt
[Params]
logo = "/images/core-cognition-logo.svg"
alt = "asds"
url = "/"
favicon = ""
blogpostId = "619f99a4cb879275fad566e6"
dataId = "61996b3541cc105c084a9af1"
