backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  # Blog config
  - name: 'blog'
    label: 'Blog'
    folder: 'content/English/blog'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'slug', name: 'url', widget: 'list', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - label: "Header"
        name: "Header"
        collapse: true
        widget: "object"
        fields:
          - {label: 'Heading', name: 'heading', widget: 'string', required: false}
          - {label: 'Summary', name: 'summary', widget: 'string', required: false}
          - {label: 'Featured Image', name: 'featuredimage', widget: 'image', required: false}
          - {label: 'Alt Text', name: 'alternativetext', widget: 'string'}
          - {label: 'Youtube Video', name: 'featuredvideo', widget: 'string', required: false, hint: 'example 6R8Bn9SmVG8'}
      - label: "Tags"
        name: "Tags"
        widget: "list"
      - {label: 'Categories', name: 'Categories', widget: 'list'}
      - {label: 'Author', name: 'Author', widget: 'list'}

      - label : "Seo section"
        name: "SeoSection"
        collapse: true
        widget: "object"
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'description', name: 'description', widget: 'text'}
          - {label: 'Social Media Image', name: 'image_OG', widget: 'image'}

  - name: 'Tags'
    label: 'Tags'
    folder: 'content/English/tags'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }

  - name: 'basic Insight'
    label: 'basic-insight'
    folder: 'content/English/basic-insight'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }

  #page Configuration

  - name: 'Pages'
    label: 'pages'
    files:
      - label : "Homepage"
        name: "Homepage"
        file: "/content/English/_index.md"
        fields:
          - { label: 'dataId', name: 'dataId', widget: 'string'}
          - { label: 'dataId', name: 'translationKey', widget: 'string'}
          - label: "Top Header"
            name: "HeaderContent"
            collapse: true
            widget: "object"
            fields:
              - { label: 'heading', name: 'heading', widget: 'string'}
              - { label: 'content', name: 'content', widget: 'text'}
              - { label: 'Featured image', name: 'featuredimage', widget: 'image'}

          - label: "Second Section"
            name: "Secondsection"
            collapse: true
            widget: "object"
            fields:
              - { label: 'heading', name: 'heading', widget: 'string'}
              - { label: 'content', name: 'content', widget: 'text'}
              - { label: 'Background Image', name: 'background_img', widget: 'image'}
